### PR TITLE
Support for .NET Standard 2.0

### PR DESCRIPTION
**Pull request by Kauser01**
Following steps were followed to compile the project in .NET Standard 2.0
-  Cloned the serilog.LogglyBulk repo
-  Deleted Properties folder, Serilog.LogglyBulkSink.csproj, packages.config
-  Ran the command "dotnet new classlib" which generated the new .csproj file.	 
-  Installed the .net core 2.0 versions of the dependent packages (Serilog, Serilog.Sinks.PeriodicBatching, Newtonsoft.Json)
Followed the same steps for Serilog.LogglyBulkSink.Tests project

### CODE REVIEW

**Comment by jamesbascle** [comment]
Hi thanks for the functioning PR!  I'll check it out sometime this week.  I for some reason never got an alert about this, so sorry for the delay.

**Comment by jdstuart** [comment]
@jamesbascle any chance you found the time to hit merge on this and upload a new NuGe package?

**Comment by jamesbascle** [comment]
I haven't.  I got side tracked by work and the Holidays.  I'll do it right now.

**Review by jamesbascle — APPROVED** [review]

**Comment by jamesbascle** [comment]
Thanks for the PR

**Comment by jamesbascle** [comment]
Having an issue getting the build to work properly with a new version incremented to 2.0.0.0.  Will try to fix soon.

**Pull request merged**
